dreport: fix shellcheck warnings in dreport
- SC2155: split declare and assign for EPOCHTIME
- SC2236: use -n instead of ! -z
- SC2254: quote case patterns
- SC2046/SC2086: quote variables and command substitutions
- SC2231: quote glob pattern in for loop
- SC2006: use $() instead of backticks for getopt
- SC2181: disable with TODO comments (getopt pattern, create_archive)
- SC2002: disable with comment (gendumpheader moved to
  openpower-debug-collector)
- Remove tools/dreport.d/dreport from .shellcheck-ignore

Tested:

Ran format-code.sh from openbmc-build-scripts.

Change-Id: I9abdc69d7fd0e2e2882571d9fd145ae10742c742
Signed-off-by: William de Abreu Pinho <williamdapinho@gmail.com>

diff --git a/tools/dreport.d/dreport b/tools/dreport.d/dreport
--- a/tools/dreport.d/dreport
+++ b/tools/dreport.d/dreport
@@ -48,7 +48,8 @@ declare -rx TYPE_RAMOOPS="ramoops"
 declare -rx SUMMARY_LOG="summary.log"
 declare -rx DREPORT_LOG="dreport.log"
 declare -rx TMP_DIR="/tmp"
-declare -rx EPOCHTIME=$(date +"%s")
+EPOCHTIME=$(date +"%s")
+declare -rx EPOCHTIME
 declare -rx TIME_STAMP="date -u"
 declare -rx PLUGIN="pl_"
 declare -rx DREPORT_SOURCE="/usr/share/dreport.d"
@@ -79,34 +80,35 @@ declare -x pid=$ZERO
 declare -x elog_id=""
 
 #Source dreport common functions
-. $DREPORT_INCLUDE/functions
+# shellcheck source=tools/dreport.d/include.d/functions
+. "$DREPORT_INCLUDE"/functions
 
 # @brief Initiate data collection based on the type.
 # @return 0 on success, error code otherwise
 function collect_data()
 {
     case $dump_type in
-        $TYPE_USER)
+        "$TYPE_USER")
             ;;
-        $TYPE_CORE)
+        "$TYPE_CORE")
             log_summary "Core: $optional_path"
             set_core_pid
             ;;
-        $TYPE_RAMOOPS)
+        "$TYPE_RAMOOPS")
             log_summary "Ramoops: $optional_path"
             ;;
-        $TYPE_ELOG)
+        "$TYPE_ELOG")
             log_summary "ELOG: $optional_path"
             elog_id=$(basename "$optional_path")
             set_elog_pid
             ;;
-        $TYPE_CHECKSTOP)
+        "$TYPE_CHECKSTOP")
             log_summary "CHECKSTOP: $optional_path"
             elog_id=$(basename "$optional_path")
             set_elog_pid
             ;;
 
-        $SUMMARY_DUMP)
+        "$SUMMARY_DUMP")
             #No data collection is required.
             return
             ;;
@@ -119,14 +121,14 @@ function collect_data()
     plugin_path=$DREPORT_SOURCE/$PLUGIN$dump_type.d
 
     # check plugin directory for this dump type?
-    if [ ! -d $plugin_path ]; then
+    if [ ! -d "$plugin_path" ]; then
         log_error "$plugin_path does not exist, skipping dump collection"
         return 0
     fi
 
     #Executes plugins based on the type.
-    for i in $plugin_path/* ; do
-        $i
+    for i in "$plugin_path"/* ; do
+        "$i"
     done
 }
 
@@ -142,7 +144,7 @@ function set_core_pid()
     file=$(printf %q "$optional_path")
 
     #matching systemd-coredump core file format.
-    pid=$(echo $file | awk -F . '{ print $5}')
+    pid=$(echo "$file" | awk -F . '{ print $5}')
 }
 
 # @brief set elog pid by reading _PID information from the elog d-bus object.
@@ -151,13 +153,13 @@ function set_core_pid()
 function set_elog_pid()
 {
     additional_data=$(busctl get-property xyz.openbmc_project.Logging \
-            $optional_path \
+            "$optional_path" \
             xyz.openbmc_project.Logging.Entry \
         AdditionalData)
 
     #read _PID data.
-    if [ ! -z "$additional_data" ]; then
-        pid=$(echo $additional_data | \
+    if [ -n "$additional_data" ]; then
+        pid=$(echo "$additional_data" | \
             awk -F _PID= '{ print ($2+0)}')
     fi
 }
@@ -178,13 +180,12 @@ function init_summary()
 function initialize()
 {
     #Dump file name
-    if [ -z $name ]; then
+    if [ -z "$name" ]; then
         name=$"obmcdump_"$dump_id"_$EPOCHTIME"
     fi
 
     #Create temporary data directory.
-    mkdir -p "$TMP_DIR/$name"
-    if [ $? -ne 0 ]; then
+    if ! mkdir -p "$TMP_DIR/$name"; then
         echo "Error: Failed to create the temporary directory."
         return $RESOURCE_UNAVAILABLE;
     fi
@@ -223,10 +224,9 @@ function initialize()
 # @brief Packaging the dump and transferring to dump location.
 function package()
 {
-    mkdir -p "$dump_dir"
-    if [ $? -ne 0 ]; then
+    if ! mkdir -p "$dump_dir"; then
         log_error "Could not create the destination directory $dump_dir"
-        dest_dir=$TMP_DIR
+        dump_dir=$TMP_DIR
     fi
 
     #tar and compress the files.
@@ -234,14 +234,21 @@ function package()
         create_archive "$name_dir" "$(dirname "$name_dir")" "$(basename "$name_dir")"
         echo "Adding Dump Header :"$HEADER_EXTENSION
         ("$HEADER_EXTENSION")
+        # shellcheck disable=SC2002
+        # gendumpheader was moved to openpower-debug-collector (commit 94bc05fc).
+        # It is unclear if this code path is still used.
         cat "$ARCHIVE_PATH" | tee -a "/tmp/dumpheader_$EPOCHTIME" > /dev/null
         mv "/tmp/dumpheader_$EPOCHTIME" "$ARCHIVE_PATH"
     else
         create_archive "$name_dir" "$(dirname "$name_dir")" "$(basename "$name_dir")"
     fi
 
+    # shellcheck disable=SC2181
+    # TODO: Refactor needed, create_archive is executed in both branches.
+    # This check captures the exit status of whichever branch ran.
+    # To be fixed in a separate patch.
     if [ $? -ne 0 ]; then
-        echo $($TIME_STAMP) "Could not create the compressed tar file"
+        echo "$($TIME_STAMP)" "Could not create the compressed tar file"
         rm -r "$name_dir"
         return $INTERNAL_FAILURE
     fi
@@ -249,15 +256,14 @@ function package()
     #remove the temporary name specific directory
     rm -r "$name_dir"
 
-    echo $($TIME_STAMP) "Report is available in $dump_dir"
+    echo "$($TIME_STAMP)" "Report is available in $dump_dir"
 
     if [ "$TMP_DIR" == "$dump_dir" ] || [ "$TMP_DIR/" == "$dump_dir" ]; then
         return $SUCCESS
     fi
 
     #copy the compressed tar file into the destination
-    cp "$ARCHIVE_PATH" "$dump_dir"
-    if [ $? -ne 0 ]; then
+    if ! cp "$ARCHIVE_PATH" "$dump_dir"; then
         echo "Failed to copy the $ARCHIVE_PATH to $dump_dir"
         rm "$ARCHIVE_PATH"
         return $INTERNAL_FAILURE
@@ -275,7 +281,7 @@ function main()
     initialize
     result=$?
     if [[ ${result} -ne $SUCCESS ]]; then
-        echo $($TIME_STAMP) "Error: Failed to initialize, Exiting"
+        echo "$($TIME_STAMP)" "Error: Failed to initialize, Exiting"
         exit;
     fi
 
@@ -288,17 +294,19 @@ function main()
     package  #package the dump
     result=$?
     if [[ ${result} -ne $SUCCESS ]]; then
-        echo $($TIME_STAMP) "Error: Failed to package, Exiting"
+        echo "$($TIME_STAMP)" "Error: Failed to package, Exiting"
     else
-        echo $($TIME_STAMP) "Successfully completed"
+        echo "$($TIME_STAMP)" "Successfully completed"
         exit;
     fi
 }
 
-TEMP=`getopt -o n:d:i:t:s:p:vqh \
-    --long name:,dir:,dumpid:,type:,size:,path:,verbose,quiet,help \
-    -- "$@"`
+TEMP=$(getopt -o n:d:i:t:s:p:vqh \
+        --long name:,dir:,dumpid:,type:,size:,path:,verbose,quiet,help \
+    -- "$@")
 
+# shellcheck disable=SC2181
+# Common getopt usage, check exit status after capturing output
 if [ $? -ne 0 ]
 then
     echo "Error: Invalid options"
