shellcheck: clean up shellcheck warnings
Shellcheck reports significant issues with the shell scripts in
this repository.  Clean them all up by following shellcheck
recommendations or squashing the warning in a few specific
cases.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: Id90c4808af04135fec28d192b4fd3b5beda49a1f

diff --git a/tools/dreport.d/dreport b/tools/dreport.d/dreport
--- a/tools/dreport.d/dreport
+++ b/tools/dreport.d/dreport
@@ -19,13 +19,13 @@ Options:
                               Identifiers include numeric characters.
                               Default dump identifier is 0
         -t, —-type <type>     Data collection type. Valid types are
-                              "user", "core", "elog".
-                              Default type is "user" initiated.
+                              \"user\", \"core\", \"elog\".
+                              Default type is \"user\" initiated.
         -p, —-path <path>     Optional contents to be included in the archive.
                               Valid paths are absolute file path or d-bus path
                               based on type parameter.
-                                 -Absolute file path for "core" type.
-                                 -elog d-bus object for "elog" type.
+                                 -Absolute file path for \"core\" type.
+                                 -elog d-bus object for \"elog\" type.
         -s, --size <size>     Maximum allowed size(in KB) of the archive.
                               Report will be truncated in case size exceeds
                               this limit. Default size is unlimited.
@@ -48,7 +48,8 @@ declare -rx TYPE_RAMOOPS="ramoops"
 declare -rx SUMMARY_LOG="summary.log"
 declare -rx DREPORT_LOG="dreport.log"
 declare -rx TMP_DIR="/tmp"
-declare -rx EPOCHTIME=$(date +"%s")
+declare -rx EPOCHTIME
+EPOCHTIME=$(date +"%s")
 declare -rx TIME_STAMP="date -u"
 declare -rx PLUGIN="pl_"
 declare -rx DREPORT_SOURCE="/usr/share/dreport.d"
@@ -79,34 +80,35 @@ declare -x pid=$ZERO
 declare -x elog_id=""
 
 #Source dreport common functions
-. $DREPORT_INCLUDE/functions
+# shellcheck source=tools/dreport.d/include.d/functions
+. "$DREPORT_INCLUDE/functions"
 
 # @brief Initiate data collection based on the type.
 # @return 0 on success, error code otherwise
 function collect_data()
 {
-    case $dump_type in
-        $TYPE_USER)
+    case "$dump_type" in
+        "$TYPE_USER")
             ;;
-        $TYPE_CORE)
+        "$TYPE_CORE")
             log_summary "Core: $optional_path"
             set_core_pid
             ;;
-        $TYPE_RAMOOPS)
+        "$TYPE_RAMOOPS")
             log_summary "Ramoops: $optional_path"
             ;;
-        $TYPE_ELOG)
+        "$TYPE_ELOG")
             log_summary "ELOG: $optional_path"
             elog_id=$(basename "$optional_path")
             set_elog_pid
             ;;
-        $TYPE_CHECKSTOP)
+        "$TYPE_CHECKSTOP")
             log_summary "CHECKSTOP: $optional_path"
             elog_id=$(basename "$optional_path")
             set_elog_pid
             ;;
 
-        $SUMMARY_DUMP)
+        "$SUMMARY_DUMP")
             #No data collection is required.
             return
             ;;
@@ -125,7 +127,7 @@ function collect_data()
     fi
 
     #Executes plugins based on the type.
-    for i in $plugin_path/* ; do
+    for i in "$plugin_path"/* ; do
        $i
     done
 }
@@ -142,7 +144,7 @@ function set_core_pid()
     file=$(printf %q "$optional_path")
 
     #matching systemd-coredump core file format.
-    pid=$(echo $file | awk -F . '{ print $5}')
+    pid=$(echo "$file" | awk -F . '{ print $5}')
 }
 
 # @brief set elog pid by reading _PID information from the elog d-bus object.
@@ -151,13 +153,13 @@ function set_core_pid()
 function set_elog_pid()
 {
     additional_data=$(busctl get-property xyz.openbmc_project.Logging \
-                             $optional_path \
+                             "$optional_path" \
                              xyz.openbmc_project.Logging.Entry \
                              AdditionalData)
 
     #read _PID data.
-    if [ ! -z "$additional_data" ]; then
-        pid=$(echo $additional_data | \
+    if [ -n "$additional_data" ]; then
+        pid=$(echo "$additional_data" | \
                    awk -F _PID= '{ print ($2+0)}')
     fi
 }
@@ -178,13 +180,12 @@ init_summary()
 function initialize()
 {
     #Dump file name
-    if [ -z $name ]; then
+    if [ -z "$name" ]; then
         name=$"obmcdump_"$dump_id"_$EPOCHTIME"
     fi
 
     #Create temporary data directory.
-    mkdir -p "$TMP_DIR/$name"
-    if [ $? -ne 0 ]; then
+    if ! mkdir -p "$TMP_DIR/$name" ; then
         echo "Error: Failed to create the temporary directory."
         return $RESOURCE_UNAVAILABLE;
     fi
@@ -199,11 +200,11 @@ function initialize()
     summary_log="$name_dir/$SUMMARY_LOG"
 
     #Type
-    if [[ ! ($dump_type = $TYPE_USER || \
-             $dump_type = $TYPE_CORE || \
-             $dump_type = $TYPE_ELOG || \
-             $dump_type = $TYPE_RAMOOPS || \
-             $dump_type = $TYPE_CHECKSTOP) ]]; then
+    if [[ ! ($dump_type = "$TYPE_USER" || \
+             $dump_type = "$TYPE_CORE" || \
+             $dump_type = "$TYPE_ELOG" || \
+             $dump_type = "$TYPE_RAMOOPS" || \
+             $dump_type = "$TYPE_CHECKSTOP") ]]; then
        log_error "Invalid -type, Only summary log is available"
        dump_type=$SUMMARY_DUMP
     fi
@@ -223,27 +224,27 @@ function initialize()
 # @brief Packaging the dump and transferring to dump location.
 function package()
 {
-    mkdir -p "$dump_dir"
-    if [ $? -ne 0 ]; then
+    if ! mkdir -p "$dump_dir" ; then
         log_error "Could not create the destination directory $dump_dir"
-        dest_dir=$TMP_DIR
+        dump_dir=$TMP_DIR
     fi
 
     #tar and compress the files.
     if [ -f "$HEADER_EXTENSION" ]; then
         tar -Jcf "$name_dir.tar.xz" -C \
-                 $(dirname "$name_dir") $(basename "$name_dir")
+                 "$(dirname "$name_dir")" "$(basename "$name_dir")"
         echo "Adding Dump Header :"$HEADER_EXTENSION
         ("$HEADER_EXTENSION")
-        cat "$name_dir.tar.xz" | tee -a "/tmp/dumpheader_$EPOCHTIME" > /dev/null
+        cat "$name_dir.tar.xz" >> "/tmp/dumpheader_$EPOCHTIME"
         mv "/tmp/dumpheader_$EPOCHTIME" "$name_dir.tar.xz"
     else
         tar -Jcf "$name_dir.tar.xz" -C \
-                 $(dirname "$name_dir") $(basename "$name_dir")
+                 "$(dirname "$name_dir")" "$(basename "$name_dir")"
     fi
 
+    # shellcheck disable=SC2181 # need output from `tar` in above if cond.
     if [ $? -ne 0 ]; then
-        echo $($TIME_STAMP) "Could not create the compressed tar file"
+        echo "$($TIME_STAMP)" "Could not create the compressed tar file"
         rm -r "$name_dir"
         return $INTERNAL_FAILURE
     fi
@@ -251,15 +252,14 @@ function package()
     #remove the temporary name specific directory
     rm -r "$name_dir"
 
-    echo $($TIME_STAMP) "Report is available in $dump_dir"
+    echo "$($TIME_STAMP)" "Report is available in $dump_dir"
 
     if [ "$TMP_DIR" == "$dump_dir" ] || [ "$TMP_DIR/" == "$dump_dir" ]; then
        return $SUCCESS
     fi
 
     #copy the compressed tar file into the destination
-    cp "$name_dir.tar.xz" "$dump_dir"
-    if [ $? -ne 0 ]; then
+    if ! cp "$name_dir.tar.xz" "$dump_dir" ; then
         echo "Failed to copy the $name_dir.tar.xz to $dump_dir"
         rm "$name_dir.tar.xz"
         return $INTERNAL_FAILURE
@@ -277,7 +277,7 @@ function main()
     initialize
     result=$?
     if [[ ${result} -ne $SUCCESS ]]; then
-        echo $($TIME_STAMP) "Error: Failed to initialize, Exiting"
+        echo "$($TIME_STAMP)" "Error: Failed to initialize, Exiting"
         exit;
     fi
 
@@ -290,17 +290,18 @@ function main()
     package  #package the dump
     result=$?
     if [[ ${result} -ne $SUCCESS ]]; then
-        echo $($TIME_STAMP) "Error: Failed to package, Exiting"
+        echo "$($TIME_STAMP)" "Error: Failed to package, Exiting"
     else
-        echo $($TIME_STAMP) "Successfully completed"
+        echo "$($TIME_STAMP)" "Successfully completed"
         exit;
     fi
 }
 
-TEMP=`getopt -o n:d:i:t:s:p:vVqh \
+TEMP=$(getopt -o n:d:i:t:s:p:vVqh \
       --long name:,dir:,dumpid:,type:,size:,path:,verbose,version,quiet,help \
-      -- "$@"`
+      -- "$@")
 
+# shellcheck disable=SC2181
 if [ $? -ne 0 ]
 then
     echo "Error: Invalid options"
