dreport: Use Custom Package instead of Header Extension
HEADER_EXTENSION has only utility functions to add headers for
packaging the dump. It is more appropriate to call the packaging
script instead which would handle the sub-logic of HEADER_EXTENSION
within the broader task of packaging the dumps.

To achieve this, a generic compressed_file variable is used.

Tested: Verified that BMC Dump is getting created.

Change-Id: I6e4dd98f7474e1a47f25b1fed322553feb09a3eb
Signed-off-by: Gopichand Paturi <gopichandpaturi@gmail.com>

diff --git a/tools/dreport.d/dreport b/tools/dreport.d/dreport
--- a/tools/dreport.d/dreport
+++ b/tools/dreport.d/dreport
@@ -56,7 +56,7 @@ declare -rx DREPORT_SOURCE="/usr/share/dreport.d"
 declare -rx DREPORT_INCLUDE="$DREPORT_SOURCE/include.d"
 declare -rx ZERO="0"
 declare -rx JOURNAL_LINE_LIMIT="500"
-declare -rx HEADER_EXTENSION="$DREPORT_INCLUDE/gendumpheader"
+declare -rx CUSTOM_PACKAGE="$DREPORT_INCLUDE/package"
 
 #Error Codes
 declare -rx SUCCESS="0"
@@ -78,9 +78,14 @@ declare -x summary_log=""
 declare -x cur_dump_size=0
 declare -x pid=$ZERO
 declare -x elog_id=""
+declare -x dDay=$(date -d @$EPOCHTIME +'%Y%m%d%H%M%S')
+declare -x serialNo=""
+declare -x FILE=""
+declare -x header_dump_name=""
 
 #Source dreport common functions
 . $DREPORT_INCLUDE/functions
+. $DREPORT_INCLUDE/opfunctions
 
 # @brief Initiate data collection based on the type.
 # @return 0 on success, error code otherwise
@@ -234,43 +239,39 @@ function package()
     fi
 
     #tar and compress the files.
-    if [ -f "$HEADER_EXTENSION" ]; then
-        tar -Jcf "$name_dir.tar.xz" -C \
-            $(dirname "$name_dir") $(basename "$name_dir")
-        echo "Adding Dump Header :"$HEADER_EXTENSION
-        ("$HEADER_EXTENSION")
-        cat "$name_dir.tar.xz" | tee -a "/tmp/dumpheader_$EPOCHTIME" > /dev/null
-        mv "/tmp/dumpheader_$EPOCHTIME" "$name_dir.tar.xz"
+    if [ -f "$CUSTOM_PACKAGE" ]; then
+        ("$CUSTOM_PACKAGE")
+        return "$SUCCESS"
     else
         tar -Jcf "$name_dir.tar.xz" -C \
-            $(dirname "$name_dir") $(basename "$name_dir")
-    fi
+            "$(dirname "$name_dir")" "$(basename "$name_dir")"
 
-    if [ $? -ne 0 ]; then
-        echo $($TIME_STAMP) "Could not create the compressed tar file"
+        # shellcheck disable=SC2181 # need output from `tar` in above if cond.
+        if [ $? -ne 0 ]; then
+            echo "$($TIME_STAMP)" "Could not create the compressed tar file"
+            rm -r "$name_dir"
+            return "$INTERNAL_FAILURE"
+        fi
+
+        #remove the temporary name specific directory
         rm -r "$name_dir"
-        return $INTERNAL_FAILURE
-    fi
 
-    #remove the temporary name specific directory
-    rm -r "$name_dir"
+        echo "$($TIME_STAMP)" "Report is available in $dump_dir"
 
-    echo $($TIME_STAMP) "Report is available in $dump_dir"
+        if [ "$TMP_DIR" == "$dump_dir" ] || [ "$TMP_DIR/" == "$dump_dir" ]; then
+            return "$SUCCESS"
+        fi
 
-    if [ "$TMP_DIR" == "$dump_dir" ] || [ "$TMP_DIR/" == "$dump_dir" ]; then
-        return $SUCCESS
-    fi
+        #copy the compressed tar file into the destination
+        cp "$name_dir.tar.xz" "$dump_dir"
+        if [ $? -ne 0 ]; then
+            echo "Failed to copy the $name_dir.tar.xz to $dump_dir"
+            rm "$name_dir.tar.xz"
+            return "$INTERNAL_FAILURE"
+        fi
 
-    #copy the compressed tar file into the destination
-    cp "$name_dir.tar.xz" "$dump_dir"
-    if [ $? -ne 0 ]; then
-        echo "Failed to copy the $name_dir.tar.xz to $dump_dir"
         rm "$name_dir.tar.xz"
-        return $INTERNAL_FAILURE
     fi
-
-    #Remove the temporary copy of the file
-    rm "$name_dir.tar.xz"
 }
 
 # @brief Main function
