dreport: Move IBM dump specific logic to HEADER Extension
1. HEADER_EXTENSION changed to packaging script
2. Move IBM dump specific logic to packaging script

Change-Id: I6e4dd98f7474e1a47f25b1fed322553feb09a3eb
Signed-off-by: Gopichand Paturi <gopichandpaturi@gmail.com>

diff --git a/tools/dreport.d/dreport b/tools/dreport.d/dreport
--- a/tools/dreport.d/dreport
+++ b/tools/dreport.d/dreport
@@ -56,7 +56,7 @@ declare -rx DREPORT_SOURCE="/usr/share/dreport.d"
 declare -rx DREPORT_INCLUDE="$DREPORT_SOURCE/include.d"
 declare -rx ZERO="0"
 declare -rx JOURNAL_LINE_LIMIT="500"
-declare -rx HEADER_EXTENSION="$DREPORT_INCLUDE/gendumpheader"
+declare -rx HEADER_EXTENSION="$DREPORT_INCLUDE/package"
 
 #Error Codes
 declare -rx SUCCESS="0"
@@ -232,42 +232,37 @@ function package()
 
     #tar and compress the files.
     if [ -f "$HEADER_EXTENSION" ]; then
-        tar -Jcf "$name_dir.tar.xz" -C \
-            $(dirname "$name_dir") $(basename "$name_dir")
-        echo "Adding Dump Header :"$HEADER_EXTENSION
         ("$HEADER_EXTENSION")
-        cat "$name_dir.tar.xz" | tee -a "/tmp/dumpheader_$EPOCHTIME" > /dev/null
-        mv "/tmp/dumpheader_$EPOCHTIME" "$name_dir.tar.xz"
     else
         tar -Jcf "$name_dir.tar.xz" -C \
             $(dirname "$name_dir") $(basename "$name_dir")
-    fi
 
-    if [ $? -ne 0 ]; then
-        echo $($TIME_STAMP) "Could not create the compressed tar file"
+        if [ $? -ne 0 ]; then
+            echo $($TIME_STAMP) "Could not create the compressed tar file"
+            rm -r "$name_dir"
+            return $INTERNAL_FAILURE
+        fi
+
+        #remove the temporary name specific directory
         rm -r "$name_dir"
-        return $INTERNAL_FAILURE
-    fi
 
-    #remove the temporary name specific directory
-    rm -r "$name_dir"
+        echo $($TIME_STAMP) "Report is available in $dump_dir"
 
-    echo $($TIME_STAMP) "Report is available in $dump_dir"
+        if [ "$TMP_DIR" == "$dump_dir" ] || [ "$TMP_DIR/" == "$dump_dir" ]; then
+            return $SUCCESS
+        fi
 
-    if [ "$TMP_DIR" == "$dump_dir" ] || [ "$TMP_DIR/" == "$dump_dir" ]; then
-        return $SUCCESS
-    fi
+        #copy the compressed tar file into the destination
+        cp "$name_dir.tar.xz" "$dump_dir"
+        if [ $? -ne 0 ]; then
+            echo "Failed to copy the $name_dir.tar.xz to $dump_dir"
+            rm "$name_dir.tar.xz"
+            return $INTERNAL_FAILURE
+        fi
 
-    #copy the compressed tar file into the destination
-    cp "$name_dir.tar.xz" "$dump_dir"
-    if [ $? -ne 0 ]; then
-        echo "Failed to copy the $name_dir.tar.xz to $dump_dir"
+        #Remove the temporary copy of the file
         rm "$name_dir.tar.xz"
-        return $INTERNAL_FAILURE
     fi
-
-    #Remove the temporary copy of the file
-    rm "$name_dir.tar.xz"
 }
 
 # @brief Main function
