dreport:IBM: Added custom package script
Change:
-Changing dump name, adding .bin as suffix on dumps
where header is applied and removing .tar.xz. This
is basically to avoid confusion as once the header
is applied it's no longer a .tar.xz file
old name: <dump name>_<dump id>_<time>.tar.xz
new name: <dump name>_<serial number>_<dump id>_<time>
-Added new package script for IBM specfic systems
this script will do the packaging.

Tested:
Post change dump getting generated with name
BMCDUMP.13F4530.00000000.20220320182233

Signed-off-by: Chirag Sharma <chirshar@in.ibm.com>
Change-Id: I70e49947123bc74c119122e9d64662f48861d42b

diff --git a/tools/dreport.d/dreport b/tools/dreport.d/dreport
--- a/tools/dreport.d/dreport
+++ b/tools/dreport.d/dreport
@@ -13,6 +13,7 @@ usage: dreport [OPTION]
 Options:
         -n, —-name <name>     Name to be used for the archive.
                               Default name format obmcdump_<id>_<epochtime>
+                              Custom format is also supported.
         -d, —-dir <directory> Archive directory to copy the compressed report.
                               Default output directory is /tmp
         -i, —-id <id>         Dump identifier to associate with the archive.
@@ -57,6 +58,7 @@ declare -rx DREPORT_INCLUDE="$DREPORT_SOURCE/include.d"
 declare -rx ZERO="0"
 declare -rx JOURNAL_LINE_LIMIT="500"
 declare -rx HEADER_EXTENSION="$DREPORT_INCLUDE/gendumpheader"
+declare -rx CUSTOM_PACKAGE="$DREPORT_INCLUDE/package"
 
 #Error Codes
 declare -rx SUCCESS="0"
@@ -78,6 +80,8 @@ declare -x summary_log=""
 declare -x cur_dump_size=0
 declare -x pid=$ZERO
 declare -x elog_id=""
+declare -x dDay=$(date -d @$EPOCHTIME +'%Y%m%d%H%M%S')
+declare -x serialNo=""
 
 #Source dreport common functions
 . $DREPORT_INCLUDE/functions
@@ -166,7 +170,11 @@ function set_elog_pid()
 # @brief Initial version of the summary log
 function init_summary()
 {
-    log_summary "Name:          $name.tar.xz"
+    if [ -f "$HEADER_EXTENSION" ]; then
+        log_summary "Name:          $name"
+    else
+        log_summary "Name:          $name.tar.xz"
+    fi
     log_summary "Epochtime:     $EPOCHTIME"
     log_summary "ID:            $dump_id"
     log_summary "Type:          $dump_type"
@@ -180,7 +188,13 @@ function initialize()
 {
     #Dump file name
     if [ -z $name ]; then
-        name=$"obmcdump_"$dump_id"_$EPOCHTIME"
+        if [ -f "$HEADER_EXTENSION" ]; then
+            fetch_serial_number
+            dump_id=$(printf %07d $dump_id)
+            name="BMCDUMP.${serialNo}.${dump_id}.${dDay}"
+        else
+            name=$"obmcdump_"$dump_id"_$EPOCHTIME"
+        fi
     fi
 
     #Create temporary data directory.
@@ -232,42 +246,37 @@ function package()
 
     #tar and compress the files.
     if [ -f "$HEADER_EXTENSION" ]; then
-        tar -Jcf "$name_dir.tar.xz" -C \
-            $(dirname "$name_dir") $(basename "$name_dir")
-        echo "Adding Dump Header :"$HEADER_EXTENSION
-        ("$HEADER_EXTENSION")
-        cat "$name_dir.tar.xz" | tee -a "/tmp/dumpheader_$EPOCHTIME" > /dev/null
-        mv "/tmp/dumpheader_$EPOCHTIME" "$name_dir.tar.xz"
+        ("$CUSTOM_PACKAGE")
     else
         tar -Jcf "$name_dir.tar.xz" -C \
-            $(dirname "$name_dir") $(basename "$name_dir")
-    fi
+            "$(dirname "$name_dir")" "$(basename "$name_dir")"
 
-    if [ $? -ne 0 ]; then
-        echo $($TIME_STAMP) "Could not create the compressed tar file"
+        # shellcheck disable=SC2181 # need output from `tar` in above if cond.
+        if [ $? -ne 0 ]; then
+            echo "$($TIME_STAMP)" "Could not create the compressed tar file"
+            rm -r "$name_dir"
+            return "$INTERNAL_FAILURE"
+        fi
+
+        #remove the temporary name specific directory
         rm -r "$name_dir"
-        return $INTERNAL_FAILURE
-    fi
 
-    #remove the temporary name specific directory
-    rm -r "$name_dir"
+        echo "$($TIME_STAMP)" "Report is available in $dump_dir"
 
-    echo $($TIME_STAMP) "Report is available in $dump_dir"
+        if [ "$TMP_DIR" == "$dump_dir" ] || [ "$TMP_DIR/" == "$dump_dir" ]; then
+            return "$SUCCESS"
+        fi
 
-    if [ "$TMP_DIR" == "$dump_dir" ] || [ "$TMP_DIR/" == "$dump_dir" ]; then
-        return $SUCCESS
-    fi
+        #copy the compressed tar file into the destination
+        cp "$name_dir.tar.xz" "$dump_dir"
+        if [ $? -ne 0 ]; then
+            echo "Failed to copy the $name_dir.tar.xz to $dump_dir"
+            rm "$name_dir.tar.xz"
+            return "$INTERNAL_FAILURE"
+        fi
 
-    #copy the compressed tar file into the destination
-    cp "$name_dir.tar.xz" "$dump_dir"
-    if [ $? -ne 0 ]; then
-        echo "Failed to copy the $name_dir.tar.xz to $dump_dir"
         rm "$name_dir.tar.xz"
-        return $INTERNAL_FAILURE
     fi
-
-    #Remove the temporary copy of the file
-    rm "$name_dir.tar.xz"
 }
 
 # @brief Main function
