dreport: Adding .bin instead of .tar.xz in dump file name
Change:
-Changing dump name, adding .bin as suffix on dumps
where header is applied and removing .tar.xz. This
is basically to avoid confusion as once the header
is applied it's no longer a .tar.xz file
old name: <dump name>_<dump id>_<time>.tar.xz
new name: <dump name>_<dump id>_<time>.bin

Test:
After this change can see dump with header is generating
as <dump name>_<dump id>_<time>.bin

Signed-off-by: Chirag Sharma <chirshar@in.ibm.com>
Change-Id: I70e49947123bc74c119122e9d64662f48861d42b

diff --git a/tools/dreport.d/dreport b/tools/dreport.d/dreport
--- a/tools/dreport.d/dreport
+++ b/tools/dreport.d/dreport
@@ -62,8 +62,8 @@ declare -x elog_id=""
 
 #Source dreport common functions
 # shellcheck source=tools/dreport.d/include.d/functions
-. "$DREPORT_INCLUDE/functions"
 . "$DREPORT_SOURCE/dcommon"
+. "$DREPORT_INCLUDE/functions"
 
 # @brief Initiate data collection based on the type.
 # @return 0 on success, error code otherwise
@@ -149,7 +149,11 @@ function set_elog_pid()
 # @brief Initial version of the summary log
 init_summary()
 {
-   log_summary "Name:          $name.tar.xz"
+   if [ -f "$HEADER_EXTENSION" ]; then
+       log_summary "Name:          $name.bin"
+   else
+       log_summary "Name:          $name.tar.xz"
+   fi
    log_summary "Epochtime:     $EPOCHTIME"
    log_summary "ID:            $dump_id"
    log_summary "Type:          $dump_type"
@@ -213,42 +217,38 @@ function package()
 
     #tar and compress the files.
     if [ -f "$HEADER_EXTENSION" ]; then
-        tar -Jcf "$name_dir.tar.xz" -C \
-                 "$(dirname "$name_dir")" "$(basename "$name_dir")"
-        echo "Adding Dump Header :"$HEADER_EXTENSION
-        ("$HEADER_EXTENSION")
-        cat "$name_dir.tar.xz" >> "/tmp/dumpheader_$EPOCHTIME"
-        mv "/tmp/dumpheader_$EPOCHTIME" "$name_dir.tar.xz"
+        ("$CUSTOM_PACKAGING")
     else
         tar -Jcf "$name_dir.tar.xz" -C \
                  "$(dirname "$name_dir")" "$(basename "$name_dir")"
-    fi
 
-    # shellcheck disable=SC2181 # need output from `tar` in above if cond.
-    if [ $? -ne 0 ]; then
-        echo "$($TIME_STAMP)" "Could not create the compressed tar file"
+        # shellcheck disable=SC2181 # need output from `tar` in above if cond.
+        if [ $? -ne 0 ]; then
+            echo "$($TIME_STAMP)" "Could not create the compressed tar file"
+            rm -r "$name_dir"
+            return "$INTERNAL_FAILURE"
+        fi
+
+        #remove the temporary name specific directory
         rm -r "$name_dir"
-        return $INTERNAL_FAILURE
-    fi
 
-    #remove the temporary name specific directory
-    rm -r "$name_dir"
+        echo "$($TIME_STAMP)" "Report is available in $dump_dir"
 
-    echo "$($TIME_STAMP)" "Report is available in $dump_dir"
+        if [ "$TMP_DIR" == "$dump_dir" ] || [ "$TMP_DIR/" == "$dump_dir" ]; then
+            return "$SUCCESS"
+        fi
 
-    if [ "$TMP_DIR" == "$dump_dir" ] || [ "$TMP_DIR/" == "$dump_dir" ]; then
-       return $SUCCESS
-    fi
+        #copy the compressed tar file into the destination
+        cp "$name_dir.tar.xz" "$dump_dir"
+        if [ $? -ne 0 ]; then
+            echo "Failed to copy the $name_dir.tar.xz to $dump_dir"
+            rm "$name_dir.tar.xz"
+            return "$INTERNAL_FAILURE"
+        fi
 
-    #copy the compressed tar file into the destination
-    if ! cp "$name_dir.tar.xz" "$dump_dir" ; then
-        echo "Failed to copy the $name_dir.tar.xz to $dump_dir"
+        #Remove the temporary copy of the file
         rm "$name_dir.tar.xz"
-        return $INTERNAL_FAILURE
     fi
-
-    #Remove the temporary copy of the file
-    rm "$name_dir.tar.xz"
 }
 
 # @brief Main function
