shellcheck: clean up shellcheck warnings
Shellcheck reports significant issues with the shell scripts in
this repository.  Clean them all up by following shellcheck
recommendations or squashing the warning in a few specific
cases.

Signed-off-by: Patrick Williams <patrick@stwcx.xyz>
Change-Id: Id90c4808af04135fec28d192b4fd3b5beda49a1f

diff --git a/tools/dreport.d/include.d/functions b/tools/dreport.d/include.d/functions
--- a/tools/dreport.d/include.d/functions
+++ b/tools/dreport.d/include.d/functions
@@ -1,4 +1,7 @@
 #!/usr/bin/env bash
+# shellcheck disable=SC2154 # lots of variables references intended
+#                           # to be passed in
+
 
 # @brief Execute the command and save the output into the dreport
 #        packaging, if it is in the user allowed dump size limit.
@@ -11,8 +14,8 @@ function add_cmd_output()
     file_name="$2"
     desc="$3"
 
-    eval $command >> "$name_dir/$file_name"
-    if [ $? -ne 0 ]; then
+    # shellcheck disable=SC2086 # intentionally wordsplit 'command'.
+    if ! eval $command >> "$name_dir/$file_name" ; then
         log_error "Failed to collect $desc"
         return 1
     fi
@@ -33,16 +36,15 @@ function add_copy_file()
     file_name="$1"
     desc="$2"
 
-    cp -r $file_name $name_dir
-    if [ $? -ne 0 ]; then
+    if ! cp -r "$file_name" "$name_dir" ; then
         log_error "Failed to copy $desc $file_name"
-        return $RESOURCE_UNAVAILABLE
+        return "$RESOURCE_UNAVAILABLE"
     fi
     if check_size "$name_dir/$(basename "$file_name")"; then
         log_info "Copied $desc $file_name"
-        return $SUCCESS
+        return "$SUCCESS"
     else
-        return $RESOURCE_UNAVAILABLE
+        return "$RESOURCE_UNAVAILABLE"
         log_warning "Skipping copy $desc $file_name"
     fi
 }
@@ -55,17 +57,16 @@ function add_copy_sym_link_file()
     file_name="$1"
     desc="$2"
 
-    cp $file_name $name_dir
-    if [ $? -ne 0 ]; then
+    if ! cp "$file_name" "$name_dir" ; then
         log_error "Failed to copy $desc $file_name"
-        return $RESOURCE_UNAVAILABLE
+        return "$RESOURCE_UNAVAILABLE"
     fi
     if check_size "$name_dir/$(basename "$file_name")"; then
         log_info "Copied $desc $file_name"
-        return $SUCCESS
+        return "$SUCCESS"
     else
         log_warning "Skipping copy $desc $file_name"
-        return $RESOURCE_UNAVAILABLE
+        return "$RESOURCE_UNAVAILABLE"
     fi
 }
 
@@ -81,46 +82,46 @@ function check_size()
     source=$1
 
     #No size check required in case dump_size is set to unlimited
-    if [ $dump_size = $UNLIMITED ]; then
+    if [ "$dump_size" = "$UNLIMITED" ]; then
         return 0
     fi
 
     #get the file or directory size
     if [[ -d $source ]] && [[ -n $source ]]; then
         tar -cf "$source.tar" -C \
-                 $(dirname "$source") $(basename "$source")
+                 "$(dirname "$source")" "$(basename "$source")"
         size=$(stat -c%s "$source.tar")
         rm "$source.tar"
     else
         size=$(stat -c%s "$source")
     fi
 
-    if [ $((size + cur_dump_size)) -gt $dump_size ]; then
+    if [ $((size + cur_dump_size)) -gt "$dump_size" ]; then
         #Exceed the allowed limit,
         #tar and compress the files and check the size
         tar -Jcf "$name_dir.tar.xz" -C \
-                  $(dirname "$name_dir") $(basename "$name_dir")
+                  "$(dirname "$name_dir")" "$(basename "$name_dir")"
         size=$(stat -c%s "$name_dir.tar.xz")
-        if [ $size -gt $dump_size ]; then
+        if [ "$size" -gt "$dump_size" ]; then
             #Remove the the specific data from the name_dir and continue
             rm "$source" "$name_dir.tar.xz"
-            return $RESOURCE_UNAVAILABLE
+            return "$RESOURCE_UNAVAILABLE"
         else
             rm "$name_dir.tar.xz"
         fi
     fi
 
     cur_dump_size=$((size + cur_dump_size))
-    return $SUCCESS
+    return "$SUCCESS"
 }
 
 # @brief log the error message
 # @param error message
 function log_error()
 {
-   echo $($TIME_STAMP) "ERROR: $*" >> $dreport_log
+   echo "$($TIME_STAMP)" "ERROR: $*" >> "$dreport_log"
    if ((quiet != TRUE)); then
-      echo $($TIME_STAMP) "ERROR: $*" >&2
+      echo "$($TIME_STAMP)" "ERROR: $*" >&2
    fi
 }
 
@@ -129,9 +130,9 @@ function log_error()
 function log_warning()
 {
     if ((verbose == TRUE)); then
-        echo $($TIME_STAMP) "WARNING: $*" >> $dreport_log
+        echo "$($TIME_STAMP)" "WARNING: $*" >> "$dreport_log"
         if ((quiet != TRUE)); then
-            echo $($TIME_STAMP) "WARNING: $*" >&2
+            echo "$($TIME_STAMP)" "WARNING: $*" >&2
         fi
     fi
 }
@@ -141,9 +142,9 @@ function log_warning()
 function log_info()
 {
     if ((verbose == TRUE)); then
-        echo $($TIME_STAMP) "INFO: $*" >> $dreport_log
+        echo "$($TIME_STAMP)" "INFO: $*" >> "$dreport_log"
         if ((quiet != TRUE)); then
-            echo $($TIME_STAMP) "INFO: $*" >&1
+            echo "$($TIME_STAMP)" "INFO: $*" >&1
         fi
     fi
 }
@@ -152,8 +153,8 @@ function log_info()
 # @param message
 function log_summary()
 {
-    echo $($TIME_STAMP) "$*" >> $summary_log
+    echo "$($TIME_STAMP)" "$*" >> "$summary_log"
     if ((quiet != TRUE)); then
-        echo $($TIME_STAMP) "$*" >&1
+        echo "$($TIME_STAMP)" "$*" >&1
     fi
 }
