dreport: Added time stamp in log messages
Change-Id: Ie6d67adbe6b499a7ad1edac7b2de945ea70b0ca4
Signed-off-by: Jayanth Othayoth <ojayanth@in.ibm.com>

diff --git a/tools/dreport b/tools/dreport
--- a/tools/dreport
+++ b/tools/dreport
@@ -346,7 +346,7 @@ function package()
              $(dirname "$name_dir") $(basename "$name_dir")
 
     if [ $? -ne 0 ]; then
-        echo "Could not create the compressed tar file"
+        echo $($TIME_STAMP) "Could not create the compressed tar file"
         rm -r "$name_dir"
         return $INTERNAL_FAILURE
     fi
@@ -354,7 +354,7 @@ function package()
     #remove the temporary name specific directory
     rm -r "$name_dir"
 
-    echo "Report is available in $dump_dir"
+    echo $($TIME_STAMP) "Report is available in $dump_dir"
 
     if [ "$TMP_DIR" == "$dump_dir" ]; then
        return $SUCCESS
@@ -363,7 +363,7 @@ function package()
     #copy the compressed tar file into the destination
     mv "$name_dir.tar.xz" "$dump_dir"
     if [ $? -ne 0 ]; then
-        echo "Failed to copy the $tar_file to $dump_dir"
+        echo $($TIME_STAMP) "Failed to copy the $tar_file to $dump_dir"
         return $INTERNAL_FAILURE
     fi
 }
@@ -371,9 +371,9 @@ function package()
 # @param error message
 function log_error()
 {
-   echo "ERROR: $@" >>"$name_dir/$DREPORT_LOG"
+   echo $($TIME_STAMP) "ERROR: $@" >>"$name_dir/$DREPORT_LOG"
    if ((quiet != TRUE)); then
-      echo "ERROR: $@" >&2
+      echo $($TIME_STAMP) "ERROR: $@" >&2
    fi
 }
 
@@ -382,9 +382,9 @@ function log_error()
 function log_warning()
 {
     if ((verbose == TRUE)); then
-        echo "WARNING: $@" >>"$name_dir/$DREPORT_LOG"
+        echo $($TIME_STAMP) "WARNING: $@" >>"$name_dir/$DREPORT_LOG"
         if ((quiet != TRUE)); then
-            echo "WARNING: $@" >&2
+            echo $($TIME_STAMP) "WARNING: $@" >&2
         fi
     fi
 }
@@ -394,9 +394,9 @@ function log_warning()
 function log_info()
 {
     if ((verbose == TRUE)); then
-        echo "INFO: $@" >>"$name_dir/$DREPORT_LOG"
+        echo $($TIME_STAMP) "INFO: $@" >>"$name_dir/$DREPORT_LOG"
         if ((quiet != TRUE)); then
-            echo "INFO: $@" >&1
+            echo $($TIME_STAMP) "INFO: $@" >&1
         fi
     fi
 }
@@ -405,9 +405,9 @@ function log_info()
 # @param message
 function log_summary()
 {
-    echo "$@" >> "$name_dir/$SUMMARY_LOG"
+    echo $($TIME_STAMP) "$@" >> "$name_dir/$SUMMARY_LOG"
     if ((quiet != TRUE)); then
-        echo "$@" >&1
+        echo $($TIME_STAMP) "$@" >&1
     fi
 }
 
@@ -419,7 +419,7 @@ function main()
     initialize
     result=$?
     if [[ ${result} -ne $SUCCESS ]]; then
-        echo $(TIME_STAMP)" Error: Failed to initialize, Exiting"
+        echo $($TIME_STAMP) "Error: Failed to initialize, Exiting"
         exit;
     fi
 
@@ -432,9 +432,9 @@ function main()
     package  #package the dump
     result=$?
     if [[ ${result} -ne $SUCCESS ]]; then
-        echo $($TIME_STAMP)" Error: Failed to package, Exiting"
+        echo $($TIME_STAMP) "Error: Failed to package, Exiting"
     else
-        echo $($TIME_STAMP)" Sucessfully completed"
+        echo $($TIME_STAMP) "Sucessfully completed"
         exit;
     fi
 }
